### ISSUE TITLE
SSH gives me user error

### ISSUE THREAD

**Issue by Sbef98** [Elive/elive-for-servers#10]
When ssh, i cannot login becuase "Please login as the user "IT" rather than the user "root"." but i'm already using the IT User

![shot-2021-12-26_14-45-21](https://user-images.githubusercontent.com/38085237/147410020-62ba2a40-fd27-408a-9898-6f76af25ae34.jpg)

**Comment by Sbef98** [comment]
P.S. Now i cannot login anymore :|

**Comment by TheTechRobo** [comment]
I've never seen that before. :face_with_head_bandage:

Are you using Ubuntu, Debian, ...?

**Comment by triantares** [comment]
Considering that that message probably comes from the server itself, can you be more specific?
i.e What Os, which script (i.e what extra commands) and were the user IT (and root) existing users on that system or created by you through running the Elive script ?

**Comment by TheTechRobo** [comment]
> If you've got fail2ban installed, you'll get banned after multiple faulty logins. Actually it's best to generate keys and not have PasswordAuthentification enabled....if it's open to the internet.

You can clearly see in the screenshot that he's using a key

**Comment by Thanatermesis** [comment]
If im not wrong, if you used the --user=IT option the user will have been updated with elive changes, this means also the .ssh dir, so try to login with another user or root and see that you should have a .ssh.old-DATE directory and just restore it

I have updated the code to be more secure now, so you may probably have been asked if copy the root ssh to your user and even if you selected 'no', your old config was moved out, now it strictly depends on the question:  https://github.com/Elive/elive-for-servers/commit/f7369273fc74a93cc512d2c9bd086d4ee4c6b499

**Comment by Sbef98** [comment]
> I've never seen that before. face_with_head_bandage
> 
> Are you using Ubuntu, Debian, ...?

I was using ubuntu 20 LTS.
Technically, the root user should be disabled by default (which means you can access it only with sudo -s), and the IT user was pre-existing. 
I

> If im not wrong, if you used the --user=IT option the user will have been updated with elive changes, this means also the .ssh dir, so try to login with another user or root and see that you should have a .ssh.old-DATE directory and just restore it
> 
> I have updated the code to be more secure now, so you may probably have been asked if copy the root ssh to your user and even if you selected 'no', your old config was moved out, now it strictly depends on the question: [f736927](https://github.com/Elive/elive-for-servers/commit/f7369273fc74a93cc512d2c9bd086d4ee4c6b499)

I see, i may have selected No by accident.
I was able to enable a serial console luckily (i'm a bit new to azure services and they're a bit over complicated!) and tried to restore the ssh settings by hand (and also through the azure tools).  Doing so, i was capable of logging in again (tho only through password authentication), but it kept ignoring the fact i added a public key to the authorized_keys.
It was pretty odd looking, so i created a new user to see what would have happened. The test user was created correctly, it had all the Elive "super powers" available immediately, and it was perfectly capable of logging in using the key (the same key) authentication method!

This was a bit confusing, i got mad, i copied the home folder of the "IT" User, deleted the user, created a new IT user, copied the files back in, notified the other team members and now everything runs perfectly smooth. (Ofc it threw A LOT of security errors and this is definitely not the suggested method, but since the usage of this VM is not critical at all i didn't care so much).
Tbh idk what happened, probably my mistake i guess! 
Here it goes:
![shot-2021-12-29_18-24-06](https://user-images.githubusercontent.com/38085237/147688394-0a247ae4-e537-4912-9576-39fe2d412a23.jpg)

**Comment by Thanatermesis** [comment]
make sure your files copied to the new user are -really- owned by the new user, run "ls -la" and see if the user and group is the correct one or is a number, like:

> -rw-r--r--   1 **thana** **thana**     353 Feb  8  2014  .zlogout

**Comment by Sbef98** [comment]
Yes they are! Thank you!
