### ISSUE TITLE
Is it possible to multiple wordpress with different subdomain/domain?

### ISSUE THREAD

**Issue by essamamdani** [Elive/elive-for-servers#11]
I like the shell script. But I have a question, how we can achieve it to manage multiple Wordpress instance with different domain/subdomain names in one server?

```bash - <(curl -fsSLg -- "https://raw.githubusercontent.com/Elive/elive-for-servers/main/install-elive-on-server.sh" ) --install=wordpress --user=user2 --password=12313 --domain=fast.com
```

```bash - <(curl -fsSLg -- "https://raw.githubusercontent.com/Elive/elive-for-servers/main/install-elive-on-server.sh" ) --install=wordpress --user=bloguser --password=12313 --domain=blog.fast.com
```

**Comment by Thanatermesis** [comment]
Hi @essamamdani , yes this is the default way of work :) , when you install a second Wordpress website it will ask you for the website name (subdomain) to use and will configure it as is
