### ISSUE TITLE
Empty MX record instruction is shown twice

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/elive-for-servers#12]
![image](https://user-images.githubusercontent.com/52163910/158890868-89467d66-e56c-4409-bb7a-7f3455e73147.png)

Also, might you consider putting the info-messages into a pager such as less? This 
![image](https://user-images.githubusercontent.com/52163910/158890935-ed4f2a55-6811-420b-aa7c-f3c657bd6379.png)
is kind of overwhelming.

Also maybe the TXT, MX, A, etc records should be categorised and all shown together.

**Comment by Thanatermesis** [comment]
fixed, but untested
