### ISSUE TITLE
Question: smtp.thetechrobo.ca: Connection refused, how to fix?

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/elive-for-servers#14]
It was working yesterday before I restarted my server. Now I'm getting connection refused on port 587 and 25. I've tried `sudo service exim4 restart` to no avail.

**Comment by TheTechRobo** [comment]
Reinstalling exim service using --force gets rid of the "connection refused" error message from mailx-send, but I still don't receive the actual messages. It used to work...

Let me try restarting the server.

**Comment by TheTechRobo** [comment]
Same problem after restarting the server :/

**Comment by TheTechRobo** [comment]
Now Exim itself is complaining. From mainlog:

```
2022-03-19 02:20:34.308 [5752] 1nVOJV-0001GJ-Mc H=mailsec.protonmail.ch [185.70.42.129]:25: SMTP timeout after initial connection: Connection timed out
```

And:

```
2022-03-19 02:22:45.380 [5995] 1nVO4V-000z4r-Uh H=gmail-smtp-in.l.google.com [2607:f8b0:4004:c09::1b]:25: SMTP timeout after initial connection: Connection timed out
```

**Comment by Thanatermesis** [comment]
The ports are probably blocked, if "ufw" is installed this is the firewall tool that the script will use to configure the ports for you automatically, if not, iptables (this one is untested)

You can use any of these tools to know if the ports are closed, or better: to know that they are enabled (must be)

By other side if you don't know how to solve it, simply re-install the email server entirely, as running the tool with the parameter "--install=email" , which will simply reconfigure / reinstall it and enable the ports and make working everything needed

**Comment by Thanatermesis** [comment]
and: if reinstalling the email server makes the issue still here is probably that your ports have been configured by something else (a clean server doesn't has this issue), so maybe you have an extra firewall installed, something that configured it, or you have configured following a howto, looks like the outgoing-25 port is blocked (not incoming)

**Comment by TheTechRobo** [comment]
Well, I ran `sudo ufw enable 587` and the same for 25 and 995; no change, so I'll maybe see if there's another firewall installed. Is there an easy way to check?

**Comment by Thanatermesis** [comment]
yes you can run "nmap" for check ports from an external machine (on a different network), there's howto's for that, by other side if this is a normal server it should work fine, instead, if the server (machine) is located as a local computer / in your house, then is more likely to be a problem in your router (your router needs to enable these ports)

**Comment by TheTechRobo** [comment]
> looks like the outgoing-25 port is blocked (not incoming)

Huh, I'm surprised you haven't noticed this.

From https://www.vultr.com/docs/what-ports-are-blocked/ : 

> [...]
> You may request these blocks be removed by [opening a support ticket](https://my.vultr.com/support/create_ticket/).
> - TCP port 25 (SMTP)
> 
> [...]

**Comment by TheTechRobo** [comment]
Wait, is there a difference between `--install=email` and `--install=exim` ? I used `--install=exim` like the readme said to.

**Comment by Thanatermesis** [comment]
no differences, you can use any of them (compatibility)

oh, yes by default vultr has this port blocked, you need to request them to enable it, they will make you a survey or something like this and you should **not** say that you want to send newsletters or any marketing like type emails, just a basic emailing system for your server, otherwise they will not enable you it (a friend happened that)

**Comment by TheTechRobo** [comment]
Closing as this is a Vultr issue.
