### ISSUE TITLE
Fails sending email to me with server details

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/elive-for-servers#15]
```
Usage: mailx-send 'to' 'subject' 'message/body'
E: Trapped error signal, please verify what failed ^, then try to fix the script and do a 'pull request' so we can have it updated and improved on: https://github.com/Elive/elive-for-servers
```

**Comment by Thanatermesis** [comment]
not a bug, hte problem is on #14

**Comment by TheTechRobo** [comment]
But if it gives a usage signal, wouldn't that mean the command was used incorrectly?

**Comment by Thanatermesis** [comment]
I assume this error is because the tool was unable to send an email and that's why throws the error and/or usage messages, so the first is to make your email delivery system work (ports problem normally, as is on #14 )
