### ISSUE TITLE
Make more modular

### ISSUE THREAD

**Issue by TheTechRobo** [Elive/elive-for-servers#2]
We really should split this into multiple files that are then all called by one "main" file.

That would really increase the readability of the codebase, IMO.

**Comment by Thanatermesis** [comment]
yes it sounds better but:
* the variables are global (used globally in different places), same for functions, etc... is more readable having all available in a same source
* there will not be more features than the already listed ones (would be too much complicated and buggy to maintain)

**Comment by triantares** [comment]
Considering the "smallness" of the script and the expectancy that it wont be needing up-scaling any time soon.... I don't think it needs to be more modular then it already is.
So I agree with @Thanatermesis  here...it's quite readable. :smile:
