### ISSUE TITLE
tmux makes switching users lose prompt echo

### ISSUE THREAD

**Issue by triantares** [Elive/elive-for-servers#3]
When I log in as a different user with a BASH shell ..... and switch to the default installed user (in our testing case "elive") using "su elive" command, due to "tmux" automagically starting .... when I kill that session, it exits and brings me back to the original bash prompt but then it does not echo what's being typed.
Simply running "tmux" from same prompt does allow me to see what I'm typing in that tmux session.

- I'm not sure whether it's a good idea to invoke starting "tmux" on login.
Personally I prefer "screen" and consider that:
- A lot of new users don't even know about terminal multiplexers and their built-in commands.

**Comment by triantares** [comment]
Just discovered that this only happens in BASH **not** when doing the same from a running ZSH ....... still might be something to reckon with to avoid future complaints.

**Comment by Thanatermesis** [comment]
zsh is enforced (switched from bash to zsh), unless the tool is (actually) bugged and doesn't do the switch, so I will close it as solved :)

**Comment by triantares** [comment]
Mmmmh, that's where Murphy's law becomes applicable :smile:  ...... so it's good to know beforehand where some complaints will be coming from.
It certainly wasn't a bug in the script .... just a "taking note of ..."

**Comment by Thanatermesis** [comment]
the zsh prompt for elive is auto-tmux-featured, bash is only bash, that's why :)
