### ISSUE TITLE
Fresh Raspberry Pi conks out on installing nginx.

### ISSUE THREAD

**Issue by triantares** [Elive/elive-for-servers#8]
Like the title says, I made a fresh install on the Rpi to test the script again.
Nginx doesn't install with the following comment about "elive-tools".
```
Insert the domain name on this server (like: johnsmith.com)
triadeHoek.nl
274 blocks
I: Installed template 'nginx'
E: invalid chars in '# gzip_comp_level;' or 'gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_disable 'MSIE [1-6]\.';', func changeconfig from install_nginx
/usr/lib/elive-tools/functions: line 1613: date * 30 + builded: : syntax error in expression (error token is ": ")
root@rasbPi-server:/home/triantares# 
```
The local "/usr/lib/elive-tools/functions" script is fine on line 1613. 

~~Looks like the line 898 in "install-elive-on-server.sh" is problematic.~~

It looks like there's an indentation problem in the the way the script writes to nginx.conf. All changeconfig gzip entries after 894 require a TAB (or 8 spaces) indentation to allow nginx to accept the nginx.conf file.

**Comment by Thanatermesis** [comment]
all fixed in last push, try again :)
