### ISSUE TITLE
adding a new user with --user= fails.

### ISSUE THREAD

**Issue by triantares** [Elive/elive-for-servers#9]
Error message:
```
cp: cannot stat '/root/.ssh': No such file or directory
E: Trapped error signal, please verify what failed ^, then try to fix the script and do a pull request so we can have it updated and improved on: https://github.com/Elive/elive-for-servers

```
Not sure why there's a '/root/.ssh' entry needed there.

Is it because 'keygen' has been commented out for root in 753 ?

**Comment by Thanatermesis** [comment]
fixed by 647d953913602e66038cedac363cabd621cb89f6

**Comment by TheTechRobo** [comment]
Thana, a tip for GitHub:

If you put "fix #$(issuenumber)", so in this case "fix #9", in the issue descrpiton, GitHub will automagically close this issue.

Actually things like "Fixes", "resolves", etc work too

**Comment by Thanatermesis** [comment]
yeah, check my recent commit messages I was just trying that and it seemed to not work :thinking:

**Comment by TheTechRobo** [comment]
I don't see anything like that.

<a href="https://ibb.co/7Jp16XY"><img src="https://i.ibb.co/3yFCL7r/image.png" alt="image" border="0"></a>

**Comment by TheTechRobo** [comment]
Ohhhhh... I was wondering why the commit messages were so vague... :P
